replicaCount: 1
maxReplicaCount: 1
environment: prd
image:
  name: nginx/nginx-ingress
  pullPolicy: Always
team: web
resources:
  requests:
    memory: "180Mi"
    cpu: "100m"
  limits:
    memory: "360Mi"

targetCPUUtilization: 60
targetMemoryUtilization: 60

c_env:
  env: prd
  CONN_COUNT: ${serviceVariable.connCount}
  DSN: ${serviceVariable.dsn}