replicaCount: 1
maxReplicaCount: 1
environment: dev
image:
  name: bitnami/nginx
  pullPolicy: Always
team: web
resources:
  requests:
    memory: "180Mi"
    cpu: "100m"
  limits:
    memory: "360Mi"

targetCPUUtilization: 60
targetMemoryUtilization: 60

c_env:
  env: dev
  CONN_COUNT: ${serviceVariable.connCount}
  DSN: ${serviceVariable.dsn}