#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  namespace: sql-scaler
#  name: {{ template "sql-scaler.fullname" . }}
#  labels:
#    app: {{ template "sql-scaler.name" . }}
#    chart: {{ template "sql-scaler.chart" . }}
#    release: {{ .Release.Name }}
#    heritage: {{ .Release.Service }}
#    environment: {{ .Values.environment }}
#    team: {{ .Values.team }}
#spec:
#  replicas: {{ .Values.replicaCount }}
#  selector:
#    matchLabels:
#      app: {{ template "sql-scaler.name" . }}
#      release: {{ .Release.Name }}
#  template:
#    metadata:
#      labels:
#        app: {{ template "sql-scaler.name" . }}
#        release: {{ .Release.Name }}
#        environment: {{ .Values.c_env.env }}
#    spec:
#      containers:
#        - name: {{ .Chart.Name }}
#          image: {{ .Values.image.name }}
#          imagePullPolicy: {{ .Values.image.pullPolicy }}
#          #readinessProbe:
#          #  httpGet:
#          #    scheme: HTTP
#          #    path: /
#          #    port: 8080
#          #  initialDelaySeconds: 10
#          #  periodSeconds: 5   
#          env:
#          {{- range $key, $value := .Values.c_env }}
#            - name: {{ $key | upper }}
#              value: {{ $value | quote }}
#          {{- end }}
#          resources:
#{{ toYaml .Values.resources | indent 12 }}
#    {{- with .Values.nodeSelector }}
#      nodeSelector:
#{{ toYaml . | indent 8 }}
#    {{- end }}
#    {{- with .Values.affinity }}
#      affinity:
#{{ toYaml . | indent 8 }}
#    {{- end }}
#    {{- with .Values.tolerations }}
#      tolerations:
#{{ toYaml . | indent 8 }}
#    {{- end }}